### PR TITLE
Potential fix for 224xx windows builds

### PR DESCRIPTION
**Pull request by mrob95**

### CODE REVIEW

**Comment by reckoner** [comment]
`COMError: (-2147467262, 'No such interface supported', (None, None, None, 0, None))`

I tried this PR and I'm on windows 11.

**Comment by mrob95** [comment]
Ah, whoops. 

Could you give the result of running `sys.getwindowsversion().platform_version`? This PR is only supposed to target insider builds

**Review by Leo40Git — APPROVED** [review]
Well... it works. By all accounts, it makes no sense, but it works.

**Comment by reckoner** [comment]
```
>>> sys.getwindowsversion().platform_version
(10, 0, 22000)
```
Seems like it works now!

**Comment by mrob95** [comment]
Thanks both for testing. I'm no longer convinced that passing `1` into `GetDesktops` is actually necessary but there's no point worrying too much about it while MS are changing things around every other build.

**Pull request merged**
